version: "3.8"
services:
  db:
    image: postgres:14
    container_name: cookout
    restart: always
    environment:
      POSTGRES_USER: cookout_user
      POSTGRES_PASSWORD: cookout_pass
      POSTGRES_DB: cookout
    ports:
      - "5431:5432"  # Map host port 5431 to container port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
